version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: auth-postgres
    restart: always
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: