spring:
  application:
    name: Auth-service
  security:
    user:
      name: user
      password: password  # Demo credentials (replace in production)
server:
  port: 9000

# The string should be longer, and It shouldn't be written here, this is just for dev purposes
jwt:
  signing-secret: secret
