spring:
  application:
    name: Auth-service
  security:
    user:
      name: "${DB_USER}"
      password: "${DB_PASSWORD}"  # Demo credentials (replace in production)
server:
  port: "${APP_PORT}"

# The string should be longer, and It shouldn't be written here, this is just for dev purposes
jwt:
  signing-secret: "${SIGNING_SECRET}"
