spring:
  application:
    name: Auth-service
  datasource:
    url: jdbc:postgresql://localhost:5433/auth-db
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
  # Disabling H2 for this profile.
  h2:
    console:
      enabled: false
server:
  port: 9000

# The string should be longer, and It shouldn't be written here, this is just for dev purposes
jwt:
  signing-secret: secret
